% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Relatório de Análise de Bioequivalência: Estudo Cross-over 2x2},
  pdfauthor={Pedro A. G. Contardi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Relatório de Análise de Bioequivalência: Estudo Cross-over 2x2}
\author{Pedro A. G. Contardi}
\date{2025-05-05}

\begin{document}
\maketitle

\hypertarget{introduuxe7uxe3o}{%
\subsection{Introdução}\label{introduuxe7uxe3o}}

O seguinte relatório foi elaborado para explicar e avaliar a
bioequivalência entre dois fármacos (\textbf{referência} e
\textbf{teste}) em um desenho cross-over 2x2.

\hypertarget{histuxf3ria-da-biodisponibilidadebioequivaluxeancia}{%
\subsection{História da
Biodisponibilidade/Bioequivalência}\label{histuxf3ria-da-biodisponibilidadebioequivaluxeancia}}

Os estudos de biodisponibilidade começaram oficialmente em 1945, com a
introdução do termo ``disponibilidade biológica''. Entre 1960-1970,
ocorreu o desenvolvimento de novas técnicas analíticas mais sensíveis,
que permitiu medir fármacos no sangue e comparar as formulações.

Em 1970, no \textbf{Canadá}, a bioequivalência passou a ser usada como
um critério regulatório e logo depois em 1977, foi adotada pela
\textbf{FDA (EUA)}, sendo fortalecida em 1984 por uma lei que permite a
aprovação de genéricos sem testes clínicos, desde que fossem
bioequivalentes ao original.

No \textbf{Brasil}, só depois da criação da \textbf{Lei dos Genéricos},
em 1999, esse tipo de avaliação virou padrão. O professor Gilberto de
Nucci foi peça-chave nesse processo, montando uma estrutura pioneira na
Unicamp e formando boa parte dos especialistas que atuam na área hoje.

Resumindo, esses estudos servem para saber \textbf{quanto, e com que
velocidade}, uma substância ativa entra na circulação e está pronta para
agir no corpo. A medição é feita com base nos níveis da substância no
sangue ao longo do tempo.

\hypertarget{importuxe2ncia-da-bioequivaluxeancia}{%
\subsection{Importância da
Bioequivalência}\label{importuxe2ncia-da-bioequivaluxeancia}}

Bioequivalência é fundamental para assegurar que duas formulações que
contêm o mesmo princípio ativo, geralmente o medicamento de marca
(\textbf{referência}) e um \textbf{genérico}, possuem o mesmo
comportamento dentro do organismo. Ou seja, liberam a substância ativa
com a mesma velocidade e quantidade, atingindo concentrações semelhantes
no sangue ao longo do tempo.

Os pontos abaixo reforçam a importância desse estudo:

\begin{itemize}
\tightlist
\item
  \textbf{Intercambialidade entre medicamentos:} Ser bioequivalentes
  garante a capacidade de trocar um medicamento por outro equivalente --
  normalmente um genérico substituindo o de marca - sem comprometer o
  tratamento.
\item
  \textbf{Necessário para aprovações regulatórias:} Tanto a
  \textbf{ANVISA (Brasil)} e \textbf{FDA (EUA)} e outras agências
  internacionais exigem estudos de bioequivalência como etapa
  \textbf{obrigatória} para aprovar medicamentos genéricos.
\item
  \textbf{Base para aprovação de genéricos:} Sem bioequivalência, não
  existe genérico aprovado. O conceito de ser genérico só é valido
  quando ele é clinicamente equivalente ao original, mesmo sem ter
  passado por todos os ensaios clínicos. Por isso que os estudos de
  bioequivalência é a principal ferramenta cientifica que valida o uso
  de genéricos.
\end{itemize}

\hypertarget{planejamento-experimental-cross-over-2x2}{%
\subsection{Planejamento Experimental: Cross-over
2x2}\label{planejamento-experimental-cross-over-2x2}}

É o planejamento padrão usado em estudos de bioequivalência. Cada
voluntário recebe os dois tratamentos, em momentos diferentes, com uma
pausa entre eles (período de washout), para evitar a interferência do
primeiro na resposta do segundo.

\begin{itemize}
\tightlist
\item
  \textbf{Dois tratamentos:} O medicamento de referência (R) e o teste
  (T) -- geralmente o genérico.
\item
  \textbf{Dois períodos:} O estudo tem duas fases de administração.
\item
  \textbf{Duas Sequências de tratamento}: Grupo 1: T -\textgreater{} R e
  Grupo 2: R -\textgreater{} T
\end{itemize}

Cada voluntário recebe ambos os tratamentos, mas em ordem diferente.
Isso garante que todo mundo seja exposto aos dois medicamentos.

Temos algumas vantagens em aplicar esse planejamento, como o controle da
variabilidade intra-indíviduo, pois a resposta de um fármaco pode variar
muito entre cada pessoa, porém dentro da mesma pessoa, essa variação
tende a ser menor. Assim, cada voluntário atua como seu próprio
controle, o que isola melhor o efeito do medicamento. Tendo o erro
experimental reduzido, a potência do teste aumenta, permitindo amostras
menores para atingir o mesmo poder estatístico comparado a um estudo
paralelo. Também é possível aplicar modelos mistos (ANOVA para
cross-over) que separam os efeitos de tratamento, período, sequência e
voluntário. Isso dá mais precisão na estimativa do efeito do tratamento.

O estudo tambem possui alguns pontos de atenção, como o período de
washout adequado. É fundamental garantir que o primeiro tratamento saiu
completamente do organismo antes do segundo, pois pode afetar o
resultado com efeito residual. Também não é muito indicado para fármacos
com meia-vida muito longa, o que implica no período de washout muito
extenso, o que pode inviabilizar o estudo.

\hypertarget{coleta-de-dados}{%
\subsection{Coleta de Dados}\label{coleta-de-dados}}

A ANVISA recomenda a inclusão de, no mínimo, 24 voluntários saudáveis,
sendo comum a inclusão de 26 para compensar as possíveis desistências ou
exclusões. As amostras de sangue são coletas em tempos pré-determinados
após a administração do medicamento, começando do tempo zero até um
período suficiente para caracterizar completamente o perfil
farmacocinético do fármaco.

\hypertarget{variuxe1veis-analisadas}{%
\subsection{Variáveis Analisadas}\label{variuxe1veis-analisadas}}

\begin{itemize}
\tightlist
\item
  \textbf{Tempo (h):} Pontos de coleta após a administração.
\item
  \textbf{Concentração Plasmática (ng/ml):} Níveis do fármaco no plasma
  em cada tempo.
\item
  \textbf{Sequência:} Ordem de administração dos tratamentos (TR ou RT).
\item
  \textbf{Período:} Primeiro ou segundo ciclo da administração.
\item
  \textbf{Tratamento:} Medicamento teste (T) ou referência (R).
\end{itemize}

\hypertarget{equauxe7uxf5es-e-estimativas-farmacocinuxe9ticas}{%
\subsection{Equações e Estimativas
Farmacocinéticas}\label{equauxe7uxf5es-e-estimativas-farmacocinuxe9ticas}}

\begin{itemize}
\tightlist
\item
  \textbf{T\_max:} Tempo máximo para atingir a concentração máxima no
  plasma.
\item
  \textbf{C\_max:} Concentração máxima observada.
\item
  \textbf{AUC\_0\_t:} Área sob a curva de concentração-tempo do tempo
  zero até o último ponto mensurável.
\item
  \textbf{AUC\_0\_inf:} Área sob a curva extrapolada até o infinito.
\item
  \textbf{Kel:} Constante de eliminação, obtida pela regressão linear da
  fase terminal da curva logarítmica de concentração-tempo.
\item
  \textbf{Meia-vida ou t1/2:} Meia-vida de eliminação, calculada como
  ln(2)/Kel.
\end{itemize}

Esses são todos os parâmetros essenciais para comparar a
biodisponibilidade entre os medicamentos teste e referência. As contas
estão detalhadas no procedimento da \emph{ANVISA: Manual de Boas
Práticas em Biodisponibilidade/Bioequivalência}, disponível em:

\href{https://docs.bvsalud.org/upload/M/2002/anvisa_Manual_etapa.pdf}{ANVISA:
Manual de Boas Práticas em Biodisponibilidade/Bioequivalência}

\hypertarget{quando-um-medicamento-uxe9-considerado-bioequivalente}{%
\subsection{Quando um medicamento é considerado
Bioequivalente?}\label{quando-um-medicamento-uxe9-considerado-bioequivalente}}

Segundo a \textbf{ANVISA}, um medicamento teste é considerado
bioequivalente ao de referência quando os intervalos de confiança de
90\% para as razoes dos parâmetros farmacocinéticos principais
(teste/referência): C\_max, AUC\_0\_t e AUC\_0\_inf -- estão
\textbf{dentro} do intervalo de \textbf{80\% a 125\%}, em escala
logarítmica.

\hypertarget{sobre-os-dados}{%
\subsection{Sobre os Dados:}\label{sobre-os-dados}}

Temos 26 voluntários escolhidos para o estudo. Analisando o banco,
observamos que dois voluntários estão faltando, sendo eles o voluntário
no \textbf{08} e \textbf{23.} Ainda assim, estamos na inclusão mínima de
\textbf{24} voluntários, ou seja, poderíamos validar essa análise na
ANVISA.

Foi medida a concentração plasmática de cada voluntário durante
\textbf{\emph{20}} vezes ao longo de cada período de administração, com
pequenos intervalos entre as primeiras coletas (0 → 0,25 → 0,5 → 0,75 →
1) que permite capturar bem o início da curva de concentração
plasmática, onde ocorre o pico (C\_max). Os intervalos vão aumentando de
forma não linear, até a coleta de 48h e 72h que confirma a eliminação
completa e garante um cálculo confiável da área sob a curva e meia-vida.

Temos também na base de dados, o período que foi administrado, qual tipo
de fármaco e a concentração em ng/ml para cada amostra coletada.

\hypertarget{estatuxedstica-descritiva}{%
\subsection{Estatística Descritiva}\label{estatuxedstica-descritiva}}

\hypertarget{importauxe7uxe3o-e-transformauxe7uxe3o-dos-dados}{%
\subsubsection{Importação e Transformação dos
Dados}\label{importauxe7uxe3o-e-transformauxe7uxe3o-dos-dados}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Pacotes Usados na Análise:}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(gridExtra)}
\FunctionTok{library}\NormalTok{(patchwork)}
\FunctionTok{library}\NormalTok{(tidyr)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 1. Importação e Preparação dos Dados}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"dados.csv"}\NormalTok{, }\AttributeTok{sep =} \StringTok{";"}\NormalTok{, }\AttributeTok{dec =} \StringTok{","}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{head}\NormalTok{(dados, }\AttributeTok{n=}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    voluntario tempo farmaco concentracao periodo
## 1           1  0.00       R         0.00       1
## 2           1  0.25       R         0.00       1
## 3           1  0.50       R         7.21       1
## 4           1  0.75       R        17.22       1
## 5           1  1.00       R        57.05       1
## 6           1  1.33       R        73.14       1
## 7           1  1.67       R        54.85       1
## 8           1  2.00       R        42.44       1
## 9           1  2.50       R        44.65       1
## 10          1  3.00       R        50.21       1
\end{verbatim}

Iremos transformar as colunas ``voluntario'', ``farmaco'' e ``periodo''
em fatores, usando o pacote \emph{dplyr}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Transformando colunas em fatores}
\NormalTok{nome\_coluna }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}}\NormalTok{ dados }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(nome\_coluna, as.factor))}
\end{Highlighting}
\end{Shaded}

Também iremos construir um objeto que contém as sequências de tratamento
por voluntário:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Construção da sequência de tratamentos (Group)}
\NormalTok{group\_seq }\OtherTok{\textless{}{-}}\NormalTok{ dados }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(voluntario, periodo, farmaco) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{distinct}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(voluntario, periodo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(voluntario) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Group =} \FunctionTok{paste}\NormalTok{(farmaco, }\AttributeTok{collapse =} \StringTok{""}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(group\_seq, }\AttributeTok{n=}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 2
##    voluntario Group
##    <fct>      <chr>
##  1 1          RT   
##  2 2          TR   
##  3 3          TR   
##  4 4          RT   
##  5 5          RT   
##  6 6          TR   
##  7 7          RT   
##  8 9          TR   
##  9 10         TR   
## 10 11         RT
\end{verbatim}

\hypertarget{cuxe1lculos-farmacocinuxe9ticos}{%
\subsubsection{Cálculos
Farmacocinéticos}\label{cuxe1lculos-farmacocinuxe9ticos}}

Iremos calcular algumas estatísticas descritivas (concentração média,
área de concentração sob a curva até um ponto k (ASCt\_k), até o
infinito (ACt\_inf), \emph{Kel}, meia-vida (t1/2)) para montarmos
tabelas por fármaco e por voluntário. De acordo com a ANVISA:

\[ ASCt_{k}= \sum_{i=1}^{k} \frac{C_{i-1}+C_{i}}{2}(t_{i}-t_{i-1}) \]
\[ ASCt_{\infty}= ASCt_{k} + \frac{C_{k}}{K_{e}} \]
\[ t_{\frac{1}{2}} = \frac{log_{2}}{K_{e}}\] Para o cálculo de
\(K_{e}\), devemos ajustar uma regressão \(log_{10}\) nos últimos pontos
de concentração (neste trabalho estou usando 6 pontos) do voluntário.
Após o ajuste, devemos pegar \(\beta1\) e multiplicar por \(-2.303\)
Para isso, usaremos a função abaixo:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 2. Cálculo dos Parâmetros Farmacocinéticos}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{calcular\_parametros }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df) \{}
\NormalTok{  Cmax }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{concentracao)}
\NormalTok{  Tmax }\OtherTok{\textless{}{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{tempo[}\FunctionTok{which.max}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{concentracao)]}
\NormalTok{  Periodo }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{periodo)}
  
\NormalTok{  ultimos\_pontos }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(tempo)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(tempo)}
  
\NormalTok{  modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{log}\NormalTok{(concentracao, }\AttributeTok{base =} \DecValTok{10}\NormalTok{) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ tempo, }\AttributeTok{data =}\NormalTok{ ultimos\_pontos)}
\NormalTok{  Kel }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo)[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{*}\NormalTok{ (}\SpecialCharTok{{-}}\FloatTok{2.303}\NormalTok{)}
\NormalTok{  MeiaVida }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(}\DecValTok{2}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ Kel}
\NormalTok{  AUC\_0\_t }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diff}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{tempo) }\SpecialCharTok{*}\NormalTok{ (}\FunctionTok{head}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{concentracao, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{tail}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{concentracao, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)) }\SpecialCharTok{/} \DecValTok{2}\NormalTok{)}
\NormalTok{  AUC\_0\_inf }\OtherTok{\textless{}{-}}\NormalTok{ AUC\_0\_t }\SpecialCharTok{+}\NormalTok{ (}\FunctionTok{tail}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{concentracao, }\DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ Kel)}
  
  \FunctionTok{return}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(Periodo, Cmax, Tmax, Kel, MeiaVida, AUC\_0\_t, AUC\_0\_inf))}
\NormalTok{\}}

\NormalTok{resultados }\OtherTok{\textless{}{-}}\NormalTok{ dados }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(voluntario, farmaco) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_modify}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{calcular\_parametros}\NormalTok{(.x))}

\NormalTok{final\_df2 }\OtherTok{\textless{}{-}}\NormalTok{ resultados }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(group\_seq, }\AttributeTok{by =} \StringTok{"voluntario"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Com esses dados calculados, podemos montar algumas tabelas descritivas:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 4. Tabela Descritiva por Tempo e Fármaco}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{tabela\_resumo }\OtherTok{\textless{}{-}}\NormalTok{ dados }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(farmaco, tempo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
\NormalTok{    Média }\OtherTok{=} \FunctionTok{mean}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{Mediana =} \FunctionTok{median}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \StringTok{\textasciigrave{}}\AttributeTok{Desvio{-}Padrão}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{sd}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \StringTok{\textasciigrave{}}\AttributeTok{Erro{-}Padrão}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{sd}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{n}\NormalTok{()),}
    \StringTok{\textasciigrave{}}\AttributeTok{CV(\%)}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{mean}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{,}
                     \DecValTok{100} \SpecialCharTok{*} \FunctionTok{sd}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{mean}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
\NormalTok{    Mínimo }\OtherTok{=} \FunctionTok{min}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\NormalTok{    Máximo }\OtherTok{=} \FunctionTok{max}\NormalTok{(concentracao, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(farmaco, tempo)}
\end{Highlighting}
\end{Shaded}

\hypertarget{tabela-descritiva---fuxe1rmaco-refuxearencia}{%
\subsubsection{Tabela Descritiva - Fármaco
Refêrencia:}\label{tabela-descritiva---fuxe1rmaco-refuxearencia}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela\_r }\OtherTok{\textless{}{-}}\NormalTok{ tabela\_resumo }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(tabela\_r, }\AttributeTok{digits =} \DecValTok{2}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1071}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1071}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1786}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1548}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
farmaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
tempo
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Média
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mediana
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Desvio-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Erro-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV(\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mínimo
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Máximo
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & NA & 0.00 & 0.00 \\
R & 0.25 & 2.71 & 0.00 & 6.32 & 1.29 & 233.44 & 0.00 & 29.72 \\
R & 0.50 & 23.57 & 20.00 & 16.58 & 3.38 & 70.34 & 0.00 & 59.65 \\
R & 0.75 & 39.23 & 36.39 & 20.44 & 4.17 & 52.10 & 7.54 & 80.01 \\
R & 1.00 & 51.24 & 49.15 & 20.38 & 4.16 & 39.76 & 18.83 & 91.35 \\
R & 1.33 & 56.49 & 53.59 & 20.32 & 4.15 & 35.97 & 25.70 & 99.46 \\
R & 1.67 & 55.79 & 51.64 & 19.47 & 3.97 & 34.90 & 25.90 & 96.94 \\
R & 2.00 & 55.19 & 50.70 & 17.98 & 3.67 & 32.57 & 33.88 & 99.41 \\
R & 2.50 & 54.39 & 49.80 & 18.57 & 3.79 & 34.14 & 28.00 & 99.12 \\
R & 3.00 & 55.00 & 48.86 & 17.87 & 3.65 & 32.50 & 32.30 & 95.98 \\
R & 4.00 & 54.00 & 49.00 & 17.85 & 3.64 & 33.06 & 27.68 & 99.12 \\
R & 6.00 & 44.78 & 39.63 & 15.20 & 3.10 & 33.96 & 26.26 & 85.36 \\
R & 8.00 & 40.09 & 38.89 & 13.66 & 2.79 & 34.07 & 20.60 & 77.24 \\
R & 10.00 & 38.72 & 38.58 & 12.34 & 2.52 & 31.87 & 18.37 & 72.71 \\
R & 12.00 & 37.21 & 37.78 & 11.37 & 2.32 & 30.54 & 21.27 & 59.53 \\
R & 16.00 & 34.37 & 31.38 & 11.62 & 2.37 & 33.80 & 18.15 & 67.26 \\
R & 20.00 & 33.76 & 33.08 & 12.82 & 2.62 & 37.96 & 14.36 & 74.17 \\
R & 24.00 & 33.04 & 30.60 & 12.64 & 2.58 & 38.27 & 15.18 & 70.85 \\
R & 48.00 & 24.48 & 22.73 & 9.56 & 1.95 & 39.07 & 10.36 & 48.01 \\
R & 72.00 & 18.65 & 19.66 & 7.83 & 1.60 & 41.97 & 6.85 & 37.84 \\
\end{longtable}

A tabela apresenta as estatísticas descritivas das concentrações
plasmáticas do fármaco de referência (R), coletadas em diferentes tempos
após administração. Foram avaliadas as seguintes medidas: média,
mediana, desvio-padrão, erro-padrão, coeficiente de variação (CV\%),
mínimo e máximo.

Observa-se um aumento progressivo das concentrações plasmáticas até
aproximadamente 1,33 h, atingindo a média máxima (C\_max) de 56,49
ng/ml. Após esse ponto, há uma estabilidade curta, seguida de uma queda
gradual, condizente com a fase de eliminação da droga. A mediana
acompanha a média em quase todos os tempos, indicando uma distribuição
simétrica dos dados na maioria dos pontos.

\hypertarget{tabela-descritiva---fuxe1rmaco-teste}{%
\subsubsection{Tabela Descritiva - Fármaco
Teste:}\label{tabela-descritiva---fuxe1rmaco-teste}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela\_t }\OtherTok{\textless{}{-}}\NormalTok{ tabela\_resumo }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(tabela\_t, }\AttributeTok{digits =} \DecValTok{2}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1071}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1071}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1786}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1548}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0952}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
farmaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
tempo
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Média
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mediana
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Desvio-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Erro-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV(\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mínimo
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Máximo
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
T & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & NA & 0.00 & 0.00 \\
T & 0.25 & 3.45 & 1.06 & 4.42 & 0.90 & 128.22 & 0.00 & 13.53 \\
T & 0.50 & 19.28 & 14.42 & 14.61 & 2.98 & 75.77 & 2.16 & 62.49 \\
T & 0.75 & 37.92 & 34.41 & 24.68 & 5.04 & 65.08 & 6.50 & 84.17 \\
T & 1.00 & 45.15 & 38.11 & 23.82 & 4.86 & 52.75 & 8.90 & 88.57 \\
T & 1.33 & 49.98 & 46.49 & 23.50 & 4.80 & 47.03 & 15.94 & 110.75 \\
T & 1.67 & 51.64 & 49.71 & 21.25 & 4.34 & 41.16 & 12.34 & 97.06 \\
T & 2.00 & 55.72 & 52.03 & 24.41 & 4.98 & 43.82 & 14.78 & 118.86 \\
T & 2.50 & 56.10 & 51.50 & 22.81 & 4.66 & 40.66 & 18.49 & 105.78 \\
T & 3.00 & 57.23 & 54.69 & 21.01 & 4.29 & 36.71 & 19.45 & 108.48 \\
T & 4.00 & 55.53 & 53.14 & 16.94 & 3.46 & 30.50 & 28.35 & 97.01 \\
T & 6.00 & 48.05 & 49.14 & 13.61 & 2.78 & 28.33 & 26.62 & 83.00 \\
T & 8.00 & 44.21 & 44.90 & 12.73 & 2.60 & 28.80 & 22.61 & 69.52 \\
T & 10.00 & 41.78 & 38.19 & 13.38 & 2.73 & 32.04 & 22.40 & 77.06 \\
T & 12.00 & 41.37 & 37.21 & 13.87 & 2.83 & 33.54 & 25.42 & 68.56 \\
T & 16.00 & 37.10 & 34.45 & 11.52 & 2.35 & 31.05 & 19.20 & 60.32 \\
T & 20.00 & 33.91 & 30.34 & 10.76 & 2.20 & 31.72 & 18.74 & 62.09 \\
T & 24.00 & 34.67 & 31.81 & 10.67 & 2.18 & 30.77 & 18.73 & 56.51 \\
T & 48.00 & 26.81 & 24.81 & 9.18 & 1.87 & 34.23 & 13.67 & 50.85 \\
T & 72.00 & 19.35 & 19.84 & 7.94 & 1.62 & 41.05 & 8.84 & 41.62 \\
\end{longtable}

O pico médio de concentração plasmática (\textbf{C\_max}) ocorre por
volta de \textbf{3,00h}, com valor médio de \textbf{57,23} ng/ml --
ligeiramente maior e mais tardio do que no fármaco de referência (que
atinge \textbf{56,49} ng/ml em \textbf{1,33h}). A mediana acompanha bem
a média até os tempos mais longos, o que indica distribuição
relativamente simétrica dos dados.

O fármaco teste tem um pico mais tardio (Tmax ≈ \textbf{3,0h}) que o
fármaco de referência (Tmax ≈ \textbf{1,33h}), o que pode indicar uma
absorção um pouco mais \textbf{lenta}, apesar das concentrações finais e
totais (ex.: valores em 24, 48, 72h) serem próximas.

O perfil do fármaco teste apresenta características compatíveis com um
produto bioequivalente: valores de \textbf{C\_max}, \textbf{AUC}, e
\textbf{meia-vida} semelhantes, além de uma variabilidade dentro dos
padrões aceitos. Pequenas diferenças em \textbf{Tmax} podem ocorrer, e
não necessariamente comprometem a bioequivalência, desde que os
intervalos de confiança \textbf{90}\% para \textbf{C\_max} e
\textbf{AUC} estejam dentro da faixa \textbf{80--125}\%.

\hypertarget{estatuxedstica-descritiva-para-as-medidas-farmacocinuxe9ticas}{%
\subsubsection{Estatística Descritiva para as Medidas
Farmacocinéticas}\label{estatuxedstica-descritiva-para-as-medidas-farmacocinuxe9ticas}}

Iremos montar algumas descritivas sobre os parâmetros farmacocinéticos
calculados, podemos usar a função abaixo:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 5. Estatísticas Descritivas por Parâmetro}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{parametros }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Tmax"}\NormalTok{, }\StringTok{"Cmax"}\NormalTok{, }\StringTok{"Kel"}\NormalTok{, }\StringTok{"MeiaVida"}\NormalTok{, }\StringTok{"AUC\_0\_t"}\NormalTok{, }\StringTok{"AUC\_0\_inf"}\NormalTok{)}

\NormalTok{resumo\_parametros }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df) \{}
\NormalTok{  df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}
\NormalTok{      Média }\OtherTok{=} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \AttributeTok{Mediana =} \FunctionTok{median}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \StringTok{\textasciigrave{}}\AttributeTok{Erro{-}Padrão}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{sd}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{n}\NormalTok{()),}
      \StringTok{\textasciigrave{}}\AttributeTok{CV(\%)}\StringTok{\textasciigrave{}} \OtherTok{=} \DecValTok{100} \SpecialCharTok{*} \FunctionTok{sd}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\NormalTok{      Mín }\OtherTok{=} \FunctionTok{min}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\NormalTok{      Máx }\OtherTok{=} \FunctionTok{max}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{    )}
\NormalTok{\}}

\NormalTok{tabela\_final }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(parametros, }\ControlFlowTok{function}\NormalTok{(param) \{}
\NormalTok{  final\_df2 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(voluntario, farmaco, }\SpecialCharTok{!!}\FunctionTok{sym}\NormalTok{(param)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{rename}\NormalTok{(}\AttributeTok{valor =} \SpecialCharTok{!!}\FunctionTok{sym}\NormalTok{(param)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(farmaco) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{resumo\_parametros}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Medida Farmacocinética}\StringTok{\textasciigrave{}} \OtherTok{=}\NormalTok{ param)}
\NormalTok{\}) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{bind\_rows}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{relocate}\NormalTok{(farmaco, }\StringTok{\textasciigrave{}}\AttributeTok{Medida Farmacocinética}\StringTok{\textasciigrave{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(farmaco, }\StringTok{\textasciigrave{}}\AttributeTok{Medida Farmacocinética}\StringTok{\textasciigrave{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Para o farmáco \textbf{REFÊRENCIA}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela\_final\_r }\OtherTok{\textless{}{-}}\NormalTok{ tabela\_final }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(farmaco}\SpecialCharTok{==}\StringTok{"R"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(tabela\_final\_r, }\AttributeTok{digits =} \DecValTok{2}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.2637}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0879}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1099}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
farmaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Medida Farmacocinética
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Média
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mediana
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Erro-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV(\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mín
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Máx
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R & AUC\_0\_inf & 4959.99 & 4047.28 & 823.64 & 81.35 & 1603.36 &
20558.27 \\
R & AUC\_0\_t & 2146.33 & 2018.18 & 145.03 & 33.10 & 1173.62 &
4156.19 \\
R & Cmax & 66.94 & 65.87 & 4.21 & 30.80 & 35.28 & 99.46 \\
R & Kel & 0.01 & 0.01 & 0.00 & 51.84 & 0.00 & 0.03 \\
R & MeiaVida & 89.18 & 64.15 & 19.65 & 107.93 & 25.98 & 492.18 \\
R & Tmax & 2.36 & 1.83 & 0.39 & 80.67 & 0.75 & 10.00 \\
\end{longtable}

Para o farmáco \textbf{TESTE}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela\_final\_t }\OtherTok{\textless{}{-}}\NormalTok{ tabela\_final }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(farmaco}\SpecialCharTok{==}\StringTok{"T"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(tabela\_final\_t, }\AttributeTok{digits =} \DecValTok{2}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.2637}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0879}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0989}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1099}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
farmaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Medida Farmacocinética
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Média
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mediana
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Erro-Padrão
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV(\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mín
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Máx
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
T & AUC\_0\_inf & 5266.78 & 4197.05 & 828.42 & 77.06 & 2062.48 &
19242.46 \\
T & AUC\_0\_t & 2276.89 & 2040.53 & 141.57 & 30.46 & 1436.86 &
4093.40 \\
T & Cmax & 67.69 & 64.60 & 4.40 & 31.82 & 38.03 & 118.86 \\
T & Kel & 0.01 & 0.01 & 0.00 & 48.48 & 0.00 & 0.02 \\
T & MeiaVida & 93.61 & 57.71 & 22.14 & 115.89 & 29.69 & 502.58 \\
T & Tmax & 2.95 & 2.50 & 0.49 & 81.47 & 0.75 & 12.00 \\
\end{longtable}

Comparando entre \textbf{REFÊRENCIA} e \textbf{TESTE}:

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1154}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1410}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1410}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1154}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1410}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1410}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.2051}}@{}}
\caption{Medidas farmacocinéticas das médias das concentrações
plasmáticas dos medicamentos de referência (R) e teste
(T)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Fármaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(T_{max}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(C_{max}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(K_{e}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(t_{1/2}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(AUC_{t}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(AUC_{\infty}\)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Fármaco
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(T_{max}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(C_{max}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(K_{e}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(t_{1/2}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(AUC_{t}\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(AUC_{\infty}\)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R & 2.36 & 66.94 & 0.01 & 89.18 & 2416.33 & 4959.99 \\
T & 2.95 & 67.69 & 0.01 & 93.61 & 2276.89 & 5266.78 \\
\end{longtable}

Pelas tabelas acima, podemos observar alguns pontos interessantes:

\begin{itemize}
\item
  O fármaco teste (T) atinge o pico mais tardiamente, podendo indicar
  uma absorção mais lenta.
\item
  Meia-vida de R e T possuem valores altos e semelhantes. \textbf{T} tem
  leve tendência de eliminar mais lentamente.
\item
  Alta variabilidade em quase todos os parâmetros.
\item
  \(K_{el}\): embora a média pareça igual (\textasciitilde0,01), o CV é
  alto (\textasciitilde48--52\%), reforçando que existem indivíduos com
  perfis de eliminação muito distintos.
\item
  As médias de \textbf{C\_max} são praticamente iguais (66,9 vs 67,7),
  com CV razoável (\textasciitilde31\%). Boa indicação de equivalência
  nesse parâmetro.
\item
  \(K_{el}\) e \textbf{Meia-vida} são bem próximas, embora muito
  variáveis. Não parecem afetar diferentemente os dois fármacos.
\end{itemize}

\hypertarget{gruxe1ficos-comparativos}{%
\subsubsection{Gráficos Comparativos:}\label{gruxe1ficos-comparativos}}

Podemos analisar alguns gráficos a respeito da descritiva que fizemos
acima:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 6. Gráficos Comparativos e Distribuição}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\CommentTok{\# Linha Cmax por voluntário}
\FunctionTok{ggplot}\NormalTok{(final\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ voluntario, }\AttributeTok{y =}\NormalTok{ Cmax, }\AttributeTok{group =}\NormalTok{ farmaco, }\AttributeTok{color =}\NormalTok{ farmaco)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{linetype =}\NormalTok{ farmaco), }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Concentração Máxima Observada por Voluntário nas Formulações R e T"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Voluntários"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Concentração Máxima Observada"}\NormalTok{, }\AttributeTok{color =} \StringTok{"Formulação"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Linha Tmax por voluntário}
\FunctionTok{ggplot}\NormalTok{(final\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ voluntario, }\AttributeTok{y =}\NormalTok{ Tmax, }\AttributeTok{group =}\NormalTok{ farmaco, }\AttributeTok{color =}\NormalTok{ farmaco)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{linetype =}\NormalTok{ farmaco), }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Tempo até atingir Cmax por Voluntário nas Formulações R e T"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Voluntários"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Tmax Observado"}\NormalTok{, }\AttributeTok{color =} \StringTok{"Formulação"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-12-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Linha ASC\_k por voluntário}
\FunctionTok{ggplot}\NormalTok{(final\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ voluntario, }\AttributeTok{y =}\NormalTok{ AUC\_0\_t, }\AttributeTok{group =}\NormalTok{ farmaco, }\AttributeTok{color =}\NormalTok{ farmaco)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{linetype =}\NormalTok{ farmaco), }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"AUC\_0\_t por Voluntário nas Formulações R e T"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Voluntários"}\NormalTok{, }\AttributeTok{y =} \StringTok{"AUC\_0\_t"}\NormalTok{, }\AttributeTok{color =} \StringTok{"Formulação"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-12-3.pdf}

As formulações \textbf{R} e \textbf{T} apresentaram perfis semelhantes
nos voluntários, mas com diferenças sutis: a formulação T mostrou, em
média, \textbf{C\_max} um pouco mais alta e \textbf{AUC0}−\textbf{t}
maior, sugerindo maior extensão da absorção; o \textbf{Tmax} também foi
levemente superior em \textbf{T}, indicando absorção mais lenta. Apesar
dessas diferenças, a alta variabilidade entre os indivíduos exige
análise estatística formal para confirmar bioequivalência.

\hypertarget{pressuposto-de-normalidade}{%
\subsubsection{Pressuposto de
Normalidade}\label{pressuposto-de-normalidade}}

Para a verificação do pressuposto de normalidade de \textbf{C\_max},
necessário para os testes estatísticos do crossover (modelo misto,
\textbf{ANOVA}), podemos analisar graficamente e pelo teste de
\textbf{Shapiro}-\textbf{wilks}, assim escrito no manual da ANVISA.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 7. Teste de Normalidade (Shapiro{-}Wilk)}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# Histogramas de Cmax e log(Cmax)}
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Cmax)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{bins =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"(a) R {-} Escala original"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Cmax"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Frequência"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Cmax)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"salmon"}\NormalTok{, }\AttributeTok{bins =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"(b) T {-} Escala original"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Cmax"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Frequência"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{log}\NormalTok{(Cmax))) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{bins =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"(c) R {-} Escala log"}\NormalTok{, }\AttributeTok{x =} \StringTok{"log(Cmax)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Frequência"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{p4 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{log}\NormalTok{(Cmax))) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"salmon"}\NormalTok{, }\AttributeTok{bins =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"(d) T {-} Escala log"}\NormalTok{, }\AttributeTok{x =} \StringTok{"log(Cmax)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Frequência"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\FunctionTok{grid.arrange}\NormalTok{(p1, p2, p3, p4, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Boxplots}
\NormalTok{box1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ farmaco, }\AttributeTok{y =}\NormalTok{ Cmax, }\AttributeTok{fill =}\NormalTok{ farmaco)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Boxplot de Cmax"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Fármaco"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Cmax"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{box2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(final\_df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ farmaco, }\AttributeTok{y =} \FunctionTok{log}\NormalTok{(Cmax), }\AttributeTok{fill =}\NormalTok{ farmaco)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Boxplot de log(Cmax)"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Fármaco"}\NormalTok{, }\AttributeTok{y =} \StringTok{"log(Cmax)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\FunctionTok{grid.arrange}\NormalTok{(box1, box2, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-13-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# QQ plots}
\NormalTok{qq1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample =}\NormalTok{ Cmax)) }\SpecialCharTok{+}
  \FunctionTok{stat\_qq}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{stat\_qq\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"QQ Plot {-} Cmax (R)"}\NormalTok{)}
\NormalTok{qq2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample =}\NormalTok{ Cmax)) }\SpecialCharTok{+}
  \FunctionTok{stat\_qq}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{stat\_qq\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"QQ Plot {-} Cmax (T)"}\NormalTok{)}
\NormalTok{qq3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample =} \FunctionTok{log}\NormalTok{(Cmax))) }\SpecialCharTok{+}
  \FunctionTok{stat\_qq}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{stat\_qq\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"QQ Plot {-} log(Cmax) (R)"}\NormalTok{)}
\NormalTok{qq4 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample =} \FunctionTok{log}\NormalTok{(Cmax))) }\SpecialCharTok{+}
  \FunctionTok{stat\_qq}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{stat\_qq\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"QQ Plot {-} log(Cmax) (T)"}\NormalTok{)}
\FunctionTok{grid.arrange}\NormalTok{(qq1, qq2, qq3, qq4, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bioeq_files/figure-latex/unnamed-chunk-13-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 7. Teste de Normalidade (Shapiro{-}Wilk)}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{shapiro\_tbl }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Farmaco     =} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"R"}\NormalTok{, }\StringTok{"T"}\NormalTok{), }\AttributeTok{each =} \DecValTok{2}\NormalTok{),}
\NormalTok{  Variável    }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Cmax"}\NormalTok{, }\StringTok{"log(Cmax)"}\NormalTok{), }\AttributeTok{times =} \DecValTok{2}\NormalTok{),}
  \AttributeTok{W           =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax)}\SpecialCharTok{$}\NormalTok{statistic,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{log}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax))}\SpecialCharTok{$}\NormalTok{statistic,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax)}\SpecialCharTok{$}\NormalTok{statistic,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{log}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax))}\SpecialCharTok{$}\NormalTok{statistic}
\NormalTok{  ),}
  \StringTok{\textasciigrave{}}\AttributeTok{p{-}valor}\StringTok{\textasciigrave{}}   \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax)}\SpecialCharTok{$}\NormalTok{p.value,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{log}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"R"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax))}\SpecialCharTok{$}\NormalTok{p.value,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax)}\SpecialCharTok{$}\NormalTok{p.value,}
    \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{log}\NormalTok{(}\FunctionTok{subset}\NormalTok{(final\_df2, farmaco }\SpecialCharTok{==} \StringTok{"T"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Cmax))}\SpecialCharTok{$}\NormalTok{p.value}
\NormalTok{  )}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Normalidade =} \FunctionTok{ifelse}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{p{-}valor}\StringTok{\textasciigrave{}} \SpecialCharTok{\textgreater{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Não Rejeita"}\NormalTok{, }\StringTok{"Rejeita"}\NormalTok{))}

\FunctionTok{kable}\NormalTok{(shapiro\_tbl, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ccccc@{}}
\toprule\noalign{}
Farmaco & Variável & W & p-valor & Normalidade \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R & Cmax & 0.936 & 0.132 & Não Rejeita \\
R & log(Cmax) & 0.944 & 0.201 & Não Rejeita \\
T & Cmax & 0.913 & 0.040 & Rejeita \\
T & log(Cmax) & 0.966 & 0.569 & Não Rejeita \\
\end{longtable}

Os testes de normalidade indicaram que a variável \textbf{C\_max}
apresenta comportamento aproximadamente normal para o fármaco \textbf{R}
(p = \textbf{0.132}), e que a transformação logarítmica melhora ainda
mais esse ajuste (\textbf{p} = \textbf{0.201}). Para o fármaco
\textbf{T}, a variável \textbf{C\_max} não segue uma distribuição normal
(p = \textbf{0.0403}), mas após a transformação logarítmica, a
normalidade é atendida (\textbf{p} = \textbf{0.569)}. Assim, os
resultados sugerem que a aplicação de log (\textbf{C\_max}) é apropriada
para análises que assumem normalidade, especialmente no caso do fármaco
\textbf{T}.

\hypertarget{anuxe1lise-descritiva-por-voluntuxe1rio}{%
\subsubsection{Análise Descritiva por
Voluntário:}\label{anuxe1lise-descritiva-por-voluntuxe1rio}}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-1}{%
\subsubsection{Descritiva por Voluntário: Voluntário
1}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-1}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-1.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-2}{%
\subsubsection{Descritiva por Voluntário: Voluntário
2}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-2}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-2.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-3}{%
\subsubsection{Descritiva por Voluntário: Voluntário
3}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-3}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-3.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-4}{%
\subsubsection{Descritiva por Voluntário: Voluntário
4}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-4}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-4.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-5}{%
\subsubsection{Descritiva por Voluntário: Voluntário
5}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-5}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-5.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-6}{%
\subsubsection{Descritiva por Voluntário: Voluntário
6}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-6}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-6.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-7}{%
\subsubsection{Descritiva por Voluntário: Voluntário
7}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-7}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-7.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-9}{%
\subsubsection{Descritiva por Voluntário: Voluntário
9}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-9}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-8.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-10}{%
\subsubsection{Descritiva por Voluntário: Voluntário
10}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-10}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-9.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-11}{%
\subsubsection{Descritiva por Voluntário: Voluntário
11}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-11}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-10.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-12}{%
\subsubsection{Descritiva por Voluntário: Voluntário
12}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-12}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-11.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-13}{%
\subsubsection{Descritiva por Voluntário: Voluntário
13}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-13}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-12.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-14}{%
\subsubsection{Descritiva por Voluntário: Voluntário
14}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-14}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-13.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-15}{%
\subsubsection{Descritiva por Voluntário: Voluntário
15}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-15}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-14.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-16}{%
\subsubsection{Descritiva por Voluntário: Voluntário
16}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-16}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-15.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-17}{%
\subsubsection{Descritiva por Voluntário: Voluntário
17}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-17}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-16.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-18}{%
\subsubsection{Descritiva por Voluntário: Voluntário
18}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-18}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-17.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-19}{%
\subsubsection{Descritiva por Voluntário: Voluntário
19}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-19}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-18.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-20}{%
\subsubsection{Descritiva por Voluntário: Voluntário
20}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-20}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-19.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-21}{%
\subsubsection{Descritiva por Voluntário: Voluntário
21}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-21}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-20.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-22}{%
\subsubsection{Descritiva por Voluntário: Voluntário
22}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-22}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-21.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-24}{%
\subsubsection{Descritiva por Voluntário: Voluntário
24}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-24}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-22.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-25}{%
\subsubsection{Descritiva por Voluntário: Voluntário
25}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-25}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-23.pdf}

\hypertarget{descritiva-por-voluntuxe1rio-voluntuxe1rio-26}{%
\subsubsection{Descritiva por Voluntário: Voluntário
26}\label{descritiva-por-voluntuxe1rio-voluntuxe1rio-26}}

\includegraphics{bioeq_files/figure-latex/por-voluntario-24.pdf}

\hypertarget{considerauxe7uxf5es-finais}{%
\subsection{Considerações Finais}\label{considerauxe7uxf5es-finais}}

A comparação entre os fármacos \textbf{R} e \textbf{T} mostrou
parâmetros farmacocinéticos médios semelhantes, com destaque para
valores próximos de \textbf{C\_max}, \textbf{AUC} e
\textbf{Meia}-\textbf{vida}. Os gráficos de concentração sugerem perfis
compatíveis, com o \textbf{T} apresentando leve atraso no \textbf{Tmax}.

Os testes de Shapiro-Wilk indicaram que os dados de \textbf{C\_max} para
o fármaco \textbf{T} não seguem distribuição normal, sendo necessário o
uso de log(\textbf{C\_max}) para atender esse pressuposto. A
transformação logarítmica também foi confirmada visualmente pelos
histogramas e gráficos de probabilidade normal, tornando-a recomendada
para análises estatísticas comparativas.

O próximo passo da análise seria aplicação da ANOVA para verificar
possíveis diferenças estatísticas entre os fármacos, considerando os
parâmetros farmacocinéticos transformados quando necessário. Em
paralelo, a comparação dos intervalos de confiança para as médias
permitirá avaliar a equivalência entre os tratamentos, especialmente
para \textbf{C\_max} e \textbf{AUC}, critérios essenciais em estudos de
bioequivalência.

\end{document}
